// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    $('#message_ready').bind('click', function(event) {
      event.stopPropagation;
      $('#message').html($('#message_input').attr('value'));
      $('#interface').hide();
      return $('#output').fadeIn('fast');
    });
    $('#output').bind('click', function(event) {
      $('#output').hide();
      return $('#interface').fadeIn('fast');
    });
    return $('#message_input').bind('keydown', function(event) {
      if (event.keyCode === 13) {
        return $('#message_ready').trigger('click');
      }
    });
  });

}).call(this);
