// Generated by CoffeeScript 1.3.3
(function() {
  var fitSize, scroller;

  scroller = function() {
    return window.scrollTo(0, 0);
  };

  fitSize = function($message) {
    var height, size, width, _results;
    $message.css('font-size', 223);
    width = $message.width();
    height = $message.height();
    size = parseInt($message.css('font-size'), 10);
    _results = [];
    while (width > 304 || height > 250) {
      size = parseInt($message.css('font-size'), 10);
      if (size < 12) {
        break;
      }
      $message.css('font-size', size - 1);
      width = $message.width();
      _results.push(height = $message.height());
    }
    return _results;
  };

  $(document).ready(function() {
    var $message, msg;
    $message = $('#message');
    msg = $('#message_input').attr('value');
    if (!window.navigator.standalone) {
      $('body').css('min-height', '480px');
      setTimeout(scroller, 100);
    }
    $('#message_ready').bind('click', function(event) {
      event.stopPropagation;
      msg = $('#message_input').attr('value');
      $message.html(msg);
      $('#interface').hide();
      setTimeout(scroller, 0);
      $('#output').fadeIn('fast');
      return fitSize($message);
    });
    $('#output').bind('click', function(event) {
      $('#output').hide();
      return $('#interface').fadeIn('fast');
    });
    return $('#message_input').bind('keydown', function(event) {
      if (event.keyCode === 13) {
        return $('#message_ready').trigger('click');
      }
    });
  });

}).call(this);
