// Generated by CoffeeScript 1.3.3
(function() {
  var fitSize, scroller;

  scroller = function() {
    return window.scrollTo(0, 0);
  };

  fitSize = function($message) {
    var height, size, width, _results;
    $message.css('font-size', 223);
    width = $message.width();
    height = $message.height();
    size = parseInt($message.css('font-size'), 10);
    _results = [];
    while (width > 304 || height > 250) {
      size = parseInt($message.css('font-size'), 10);
      if (size < 12) {
        break;
      }
      $message.css('font-size', size - 1);
      width = $message.width();
      _results.push(height = $message.height());
    }
    return _results;
  };

  $(document).ready(function() {
    var $interface, $message, $message_input, $message_show, $output;
    $message = $('#message');
    $message_input = $('#message_input');
    $message_show = $('#message_show');
    $interface = $('#interface');
    $output = $('#output');
    if (!window.navigator.standalone) {
      $('body').css('min-height', '480px');
      setTimeout(scroller, 100);
    }
    $message_show.bind('click', function(event) {
      var msg;
      event.stopPropagation();
      msg = $message_input.attr('value');
      $message.html(msg);
      $interface.hide();
      setTimeout(scroller, 0);
      $output.fadeIn('fast');
      $output.css('display', 'table');
      return fitSize($message);
    });
    $output.bind('click', function(event) {
      $output.hide();
      $interface.fadeIn('fast');
      return $message_input.focus();
    });
    $message_input.bind('keyup', function(event) {
      var msg;
      msg = $message_input.attr('value');
      if (event.keyCode === 13 && msg !== '') {
        return $message_show.trigger('click');
      } else if (msg !== '') {
        return $message_show.fadeIn('medium');
      } else {
        return $message_show.fadeOut('fast');
      }
    });
    return $('#color_toggle').bind('click', function(event) {
      event.preventDefault();
      return $('#colors').toggle();
    });
  });

}).call(this);
